// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module LoadAct (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_in_act_V_AWVALID,
        m_axi_in_act_V_AWREADY,
        m_axi_in_act_V_AWADDR,
        m_axi_in_act_V_AWID,
        m_axi_in_act_V_AWLEN,
        m_axi_in_act_V_AWSIZE,
        m_axi_in_act_V_AWBURST,
        m_axi_in_act_V_AWLOCK,
        m_axi_in_act_V_AWCACHE,
        m_axi_in_act_V_AWPROT,
        m_axi_in_act_V_AWQOS,
        m_axi_in_act_V_AWREGION,
        m_axi_in_act_V_AWUSER,
        m_axi_in_act_V_WVALID,
        m_axi_in_act_V_WREADY,
        m_axi_in_act_V_WDATA,
        m_axi_in_act_V_WSTRB,
        m_axi_in_act_V_WLAST,
        m_axi_in_act_V_WID,
        m_axi_in_act_V_WUSER,
        m_axi_in_act_V_ARVALID,
        m_axi_in_act_V_ARREADY,
        m_axi_in_act_V_ARADDR,
        m_axi_in_act_V_ARID,
        m_axi_in_act_V_ARLEN,
        m_axi_in_act_V_ARSIZE,
        m_axi_in_act_V_ARBURST,
        m_axi_in_act_V_ARLOCK,
        m_axi_in_act_V_ARCACHE,
        m_axi_in_act_V_ARPROT,
        m_axi_in_act_V_ARQOS,
        m_axi_in_act_V_ARREGION,
        m_axi_in_act_V_ARUSER,
        m_axi_in_act_V_RVALID,
        m_axi_in_act_V_RREADY,
        m_axi_in_act_V_RDATA,
        m_axi_in_act_V_RLAST,
        m_axi_in_act_V_RID,
        m_axi_in_act_V_RUSER,
        m_axi_in_act_V_RRESP,
        m_axi_in_act_V_BVALID,
        m_axi_in_act_V_BREADY,
        m_axi_in_act_V_BRESP,
        m_axi_in_act_V_BID,
        m_axi_in_act_V_BUSER,
        in_act_V_offset,
        act_buff_0_V_address0,
        act_buff_0_V_ce0,
        act_buff_0_V_we0,
        act_buff_0_V_d0,
        act_buff_0_V_address1,
        act_buff_0_V_ce1,
        act_buff_0_V_we1,
        act_buff_0_V_d1,
        act_buff_1_V_address0,
        act_buff_1_V_ce0,
        act_buff_1_V_we0,
        act_buff_1_V_d0,
        act_buff_1_V_address1,
        act_buff_1_V_ce1,
        act_buff_1_V_we1,
        act_buff_1_V_d1,
        act_buff_2_V_address0,
        act_buff_2_V_ce0,
        act_buff_2_V_we0,
        act_buff_2_V_d0,
        act_buff_2_V_address1,
        act_buff_2_V_ce1,
        act_buff_2_V_we1,
        act_buff_2_V_d1,
        act_buff_3_V_address0,
        act_buff_3_V_ce0,
        act_buff_3_V_we0,
        act_buff_3_V_d0,
        act_buff_3_V_address1,
        act_buff_3_V_ce1,
        act_buff_3_V_we1,
        act_buff_3_V_d1,
        act_buff_4_V_address0,
        act_buff_4_V_ce0,
        act_buff_4_V_we0,
        act_buff_4_V_d0,
        act_buff_4_V_address1,
        act_buff_4_V_ce1,
        act_buff_4_V_we1,
        act_buff_4_V_d1,
        act_buff_5_V_address0,
        act_buff_5_V_ce0,
        act_buff_5_V_we0,
        act_buff_5_V_d0,
        act_buff_5_V_address1,
        act_buff_5_V_ce1,
        act_buff_5_V_we1,
        act_buff_5_V_d1,
        act_buff_6_V_address0,
        act_buff_6_V_ce0,
        act_buff_6_V_we0,
        act_buff_6_V_d0,
        act_buff_6_V_address1,
        act_buff_6_V_ce1,
        act_buff_6_V_we1,
        act_buff_6_V_d1,
        act_buff_7_V_address0,
        act_buff_7_V_ce0,
        act_buff_7_V_we0,
        act_buff_7_V_d0,
        act_buff_7_V_address1,
        act_buff_7_V_ce1,
        act_buff_7_V_we1,
        act_buff_7_V_d1,
        act_load_length
);

parameter    ap_ST_fsm_state1 = 12'd1;
parameter    ap_ST_fsm_state2 = 12'd2;
parameter    ap_ST_fsm_state3 = 12'd4;
parameter    ap_ST_fsm_state4 = 12'd8;
parameter    ap_ST_fsm_state5 = 12'd16;
parameter    ap_ST_fsm_state6 = 12'd32;
parameter    ap_ST_fsm_state7 = 12'd64;
parameter    ap_ST_fsm_pp0_stage0 = 12'd128;
parameter    ap_ST_fsm_pp0_stage1 = 12'd256;
parameter    ap_ST_fsm_pp0_stage2 = 12'd512;
parameter    ap_ST_fsm_pp0_stage3 = 12'd1024;
parameter    ap_ST_fsm_state14 = 12'd2048;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_in_act_V_AWVALID;
input   m_axi_in_act_V_AWREADY;
output  [31:0] m_axi_in_act_V_AWADDR;
output  [0:0] m_axi_in_act_V_AWID;
output  [31:0] m_axi_in_act_V_AWLEN;
output  [2:0] m_axi_in_act_V_AWSIZE;
output  [1:0] m_axi_in_act_V_AWBURST;
output  [1:0] m_axi_in_act_V_AWLOCK;
output  [3:0] m_axi_in_act_V_AWCACHE;
output  [2:0] m_axi_in_act_V_AWPROT;
output  [3:0] m_axi_in_act_V_AWQOS;
output  [3:0] m_axi_in_act_V_AWREGION;
output  [0:0] m_axi_in_act_V_AWUSER;
output   m_axi_in_act_V_WVALID;
input   m_axi_in_act_V_WREADY;
output  [511:0] m_axi_in_act_V_WDATA;
output  [63:0] m_axi_in_act_V_WSTRB;
output   m_axi_in_act_V_WLAST;
output  [0:0] m_axi_in_act_V_WID;
output  [0:0] m_axi_in_act_V_WUSER;
output   m_axi_in_act_V_ARVALID;
input   m_axi_in_act_V_ARREADY;
output  [31:0] m_axi_in_act_V_ARADDR;
output  [0:0] m_axi_in_act_V_ARID;
output  [31:0] m_axi_in_act_V_ARLEN;
output  [2:0] m_axi_in_act_V_ARSIZE;
output  [1:0] m_axi_in_act_V_ARBURST;
output  [1:0] m_axi_in_act_V_ARLOCK;
output  [3:0] m_axi_in_act_V_ARCACHE;
output  [2:0] m_axi_in_act_V_ARPROT;
output  [3:0] m_axi_in_act_V_ARQOS;
output  [3:0] m_axi_in_act_V_ARREGION;
output  [0:0] m_axi_in_act_V_ARUSER;
input   m_axi_in_act_V_RVALID;
output   m_axi_in_act_V_RREADY;
input  [511:0] m_axi_in_act_V_RDATA;
input   m_axi_in_act_V_RLAST;
input  [0:0] m_axi_in_act_V_RID;
input  [0:0] m_axi_in_act_V_RUSER;
input  [1:0] m_axi_in_act_V_RRESP;
input   m_axi_in_act_V_BVALID;
output   m_axi_in_act_V_BREADY;
input  [1:0] m_axi_in_act_V_BRESP;
input  [0:0] m_axi_in_act_V_BID;
input  [0:0] m_axi_in_act_V_BUSER;
input  [25:0] in_act_V_offset;
output  [11:0] act_buff_0_V_address0;
output   act_buff_0_V_ce0;
output   act_buff_0_V_we0;
output  [7:0] act_buff_0_V_d0;
output  [11:0] act_buff_0_V_address1;
output   act_buff_0_V_ce1;
output   act_buff_0_V_we1;
output  [7:0] act_buff_0_V_d1;
output  [11:0] act_buff_1_V_address0;
output   act_buff_1_V_ce0;
output   act_buff_1_V_we0;
output  [7:0] act_buff_1_V_d0;
output  [11:0] act_buff_1_V_address1;
output   act_buff_1_V_ce1;
output   act_buff_1_V_we1;
output  [7:0] act_buff_1_V_d1;
output  [11:0] act_buff_2_V_address0;
output   act_buff_2_V_ce0;
output   act_buff_2_V_we0;
output  [7:0] act_buff_2_V_d0;
output  [11:0] act_buff_2_V_address1;
output   act_buff_2_V_ce1;
output   act_buff_2_V_we1;
output  [7:0] act_buff_2_V_d1;
output  [11:0] act_buff_3_V_address0;
output   act_buff_3_V_ce0;
output   act_buff_3_V_we0;
output  [7:0] act_buff_3_V_d0;
output  [11:0] act_buff_3_V_address1;
output   act_buff_3_V_ce1;
output   act_buff_3_V_we1;
output  [7:0] act_buff_3_V_d1;
output  [11:0] act_buff_4_V_address0;
output   act_buff_4_V_ce0;
output   act_buff_4_V_we0;
output  [7:0] act_buff_4_V_d0;
output  [11:0] act_buff_4_V_address1;
output   act_buff_4_V_ce1;
output   act_buff_4_V_we1;
output  [7:0] act_buff_4_V_d1;
output  [11:0] act_buff_5_V_address0;
output   act_buff_5_V_ce0;
output   act_buff_5_V_we0;
output  [7:0] act_buff_5_V_d0;
output  [11:0] act_buff_5_V_address1;
output   act_buff_5_V_ce1;
output   act_buff_5_V_we1;
output  [7:0] act_buff_5_V_d1;
output  [11:0] act_buff_6_V_address0;
output   act_buff_6_V_ce0;
output   act_buff_6_V_we0;
output  [7:0] act_buff_6_V_d0;
output  [11:0] act_buff_6_V_address1;
output   act_buff_6_V_ce1;
output   act_buff_6_V_we1;
output  [7:0] act_buff_6_V_d1;
output  [11:0] act_buff_7_V_address0;
output   act_buff_7_V_ce0;
output   act_buff_7_V_we0;
output  [7:0] act_buff_7_V_d0;
output  [11:0] act_buff_7_V_address1;
output   act_buff_7_V_ce1;
output   act_buff_7_V_we1;
output  [7:0] act_buff_7_V_d1;
input  [31:0] act_load_length;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg m_axi_in_act_V_ARVALID;
reg m_axi_in_act_V_RREADY;
reg[11:0] act_buff_0_V_address0;
reg act_buff_0_V_ce0;
reg act_buff_0_V_we0;
reg[7:0] act_buff_0_V_d0;
reg[11:0] act_buff_0_V_address1;
reg act_buff_0_V_ce1;
reg act_buff_0_V_we1;
reg[7:0] act_buff_0_V_d1;
reg[11:0] act_buff_1_V_address0;
reg act_buff_1_V_ce0;
reg act_buff_1_V_we0;
reg[7:0] act_buff_1_V_d0;
reg[11:0] act_buff_1_V_address1;
reg act_buff_1_V_ce1;
reg act_buff_1_V_we1;
reg[7:0] act_buff_1_V_d1;
reg[11:0] act_buff_2_V_address0;
reg act_buff_2_V_ce0;
reg act_buff_2_V_we0;
reg[7:0] act_buff_2_V_d0;
reg[11:0] act_buff_2_V_address1;
reg act_buff_2_V_ce1;
reg act_buff_2_V_we1;
reg[7:0] act_buff_2_V_d1;
reg[11:0] act_buff_3_V_address0;
reg act_buff_3_V_ce0;
reg act_buff_3_V_we0;
reg[7:0] act_buff_3_V_d0;
reg[11:0] act_buff_3_V_address1;
reg act_buff_3_V_ce1;
reg act_buff_3_V_we1;
reg[7:0] act_buff_3_V_d1;
reg[11:0] act_buff_4_V_address0;
reg act_buff_4_V_ce0;
reg act_buff_4_V_we0;
reg[7:0] act_buff_4_V_d0;
reg[11:0] act_buff_4_V_address1;
reg act_buff_4_V_ce1;
reg act_buff_4_V_we1;
reg[7:0] act_buff_4_V_d1;
reg[11:0] act_buff_5_V_address0;
reg act_buff_5_V_ce0;
reg act_buff_5_V_we0;
reg[7:0] act_buff_5_V_d0;
reg[11:0] act_buff_5_V_address1;
reg act_buff_5_V_ce1;
reg act_buff_5_V_we1;
reg[7:0] act_buff_5_V_d1;
reg[11:0] act_buff_6_V_address0;
reg act_buff_6_V_ce0;
reg act_buff_6_V_we0;
reg[7:0] act_buff_6_V_d0;
reg[11:0] act_buff_6_V_address1;
reg act_buff_6_V_ce1;
reg act_buff_6_V_we1;
reg[7:0] act_buff_6_V_d1;
reg[11:0] act_buff_7_V_address0;
reg act_buff_7_V_ce0;
reg act_buff_7_V_we0;
reg[7:0] act_buff_7_V_d0;
reg[11:0] act_buff_7_V_address1;
reg act_buff_7_V_ce1;
reg act_buff_7_V_we1;
reg[7:0] act_buff_7_V_d1;

(* fsm_encoding = "none" *) reg   [11:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    in_act_V_blk_n_AR;
reg    in_act_V_blk_n_R;
wire    ap_CS_fsm_pp0_stage1;
reg    ap_enable_reg_pp0_iter0;
wire    ap_block_pp0_stage1;
reg   [0:0] icmp_ln60_reg_1768;
reg   [30:0] i_0_reg_942;
wire   [0:0] icmp_ln60_fu_968_p2;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_block_state8_pp0_stage0_iter0;
wire    ap_block_state12_pp0_stage0_iter1;
wire    ap_block_pp0_stage0_11001;
reg   [0:0] icmp_ln60_reg_1768_pp0_iter1_reg;
wire   [30:0] i_fu_973_p2;
reg   [30:0] i_reg_1772;
wire   [28:0] trunc_ln69_fu_979_p1;
reg   [28:0] trunc_ln69_reg_1777;
wire   [7:0] trunc_ln647_fu_983_p1;
reg   [7:0] trunc_ln647_reg_1782;
reg    ap_block_state9_pp0_stage1_iter0;
wire    ap_block_state13_pp0_stage1_iter1;
reg    ap_block_pp0_stage1_11001;
reg   [7:0] p_Result_3_0_1_reg_1787;
reg   [7:0] p_Result_3_0_2_reg_1792;
reg   [7:0] p_Result_3_0_3_reg_1797;
reg   [7:0] p_Result_3_0_4_reg_1802;
reg   [7:0] p_Result_3_0_5_reg_1807;
reg   [7:0] p_Result_3_0_6_reg_1812;
reg   [7:0] p_Result_3_0_7_reg_1817;
reg   [7:0] p_Result_3_1_reg_1822;
reg   [7:0] p_Result_3_1_1_reg_1827;
reg   [7:0] p_Result_3_1_2_reg_1832;
reg   [7:0] p_Result_3_1_3_reg_1837;
reg   [7:0] p_Result_3_1_4_reg_1842;
reg   [7:0] p_Result_3_1_5_reg_1847;
reg   [7:0] p_Result_3_1_6_reg_1852;
reg   [7:0] p_Result_3_1_7_reg_1857;
reg   [7:0] p_Result_3_2_reg_1862;
reg   [7:0] p_Result_3_2_1_reg_1867;
reg   [7:0] p_Result_3_2_2_reg_1872;
reg   [7:0] p_Result_3_2_3_reg_1877;
reg   [7:0] p_Result_3_2_4_reg_1882;
reg   [7:0] p_Result_3_2_5_reg_1887;
reg   [7:0] p_Result_3_2_6_reg_1892;
reg   [7:0] p_Result_3_2_7_reg_1897;
reg   [7:0] p_Result_3_3_reg_1902;
reg   [7:0] p_Result_3_3_1_reg_1907;
reg   [7:0] p_Result_3_3_2_reg_1912;
reg   [7:0] p_Result_3_3_3_reg_1917;
reg   [7:0] p_Result_3_3_4_reg_1922;
reg   [7:0] p_Result_3_3_5_reg_1927;
reg   [7:0] p_Result_3_3_6_reg_1932;
reg   [7:0] p_Result_3_3_7_reg_1937;
reg   [7:0] p_Result_3_4_reg_1942;
reg   [7:0] p_Result_3_4_1_reg_1947;
reg   [7:0] p_Result_3_4_2_reg_1952;
reg   [7:0] p_Result_3_4_3_reg_1957;
reg   [7:0] p_Result_3_4_4_reg_1962;
reg   [7:0] p_Result_3_4_5_reg_1967;
reg   [7:0] p_Result_3_4_6_reg_1972;
reg   [7:0] p_Result_3_4_7_reg_1977;
reg   [7:0] p_Result_3_5_reg_1982;
reg   [7:0] p_Result_3_5_1_reg_1987;
reg   [7:0] p_Result_3_5_2_reg_1992;
reg   [7:0] p_Result_3_5_3_reg_1997;
reg   [7:0] p_Result_3_5_4_reg_2002;
reg   [7:0] p_Result_3_5_5_reg_2007;
reg   [7:0] p_Result_3_5_6_reg_2012;
reg   [7:0] p_Result_3_5_7_reg_2017;
reg   [7:0] p_Result_3_6_reg_2022;
reg   [7:0] p_Result_3_6_1_reg_2027;
reg   [7:0] p_Result_3_6_2_reg_2032;
reg   [7:0] p_Result_3_6_3_reg_2037;
reg   [7:0] p_Result_3_6_4_reg_2042;
reg   [7:0] p_Result_3_6_5_reg_2047;
reg   [7:0] p_Result_3_6_6_reg_2052;
reg   [7:0] p_Result_3_6_7_reg_2057;
reg   [7:0] p_Result_3_7_reg_2062;
reg   [7:0] p_Result_3_7_1_reg_2067;
reg   [7:0] p_Result_3_7_2_reg_2072;
reg   [7:0] p_Result_3_7_3_reg_2077;
reg   [7:0] p_Result_3_7_4_reg_2082;
reg   [7:0] p_Result_3_7_5_reg_2087;
reg   [7:0] p_Result_3_7_6_reg_2092;
reg   [7:0] p_Result_3_7_7_reg_2097;
wire  signed [31:0] shl_ln_fu_1617_p3;
reg  signed [31:0] shl_ln_reg_2102;
wire    ap_CS_fsm_pp0_stage2;
wire    ap_block_state10_pp0_stage2_iter0;
wire    ap_block_pp0_stage2_11001;
wire    ap_CS_fsm_state7;
wire    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state8;
reg    ap_enable_reg_pp0_iter1;
wire    ap_block_state11_pp0_stage3_iter0;
wire    ap_block_pp0_stage3_subdone;
wire    ap_CS_fsm_pp0_stage3;
reg    ap_block_pp0_stage1_subdone;
reg   [30:0] ap_phi_mux_i_0_phi_fu_946_p4;
wire    ap_block_pp0_stage0;
wire  signed [63:0] sext_ln69_fu_1624_p1;
wire    ap_block_pp0_stage2;
wire  signed [63:0] sext_ln69_1_fu_1642_p1;
wire  signed [63:0] sext_ln69_2_fu_1659_p1;
wire    ap_block_pp0_stage3;
wire  signed [63:0] sext_ln69_3_fu_1676_p1;
wire  signed [63:0] sext_ln69_4_fu_1693_p1;
wire  signed [63:0] sext_ln69_5_fu_1710_p1;
wire  signed [63:0] sext_ln69_6_fu_1727_p1;
wire  signed [63:0] sext_ln69_7_fu_1744_p1;
wire   [63:0] zext_ln57_fu_953_p1;
wire    ap_block_pp0_stage3_11001;
wire   [31:0] zext_ln60_fu_964_p1;
wire   [31:0] or_ln69_fu_1636_p2;
wire   [31:0] or_ln69_1_fu_1654_p2;
wire   [31:0] or_ln69_2_fu_1671_p2;
wire   [31:0] or_ln69_3_fu_1688_p2;
wire   [31:0] or_ln69_4_fu_1705_p2;
wire   [31:0] or_ln69_5_fu_1722_p2;
wire   [31:0] or_ln69_6_fu_1739_p2;
wire    ap_CS_fsm_state14;
reg   [11:0] ap_NS_fsm;
wire    ap_block_pp0_stage2_subdone;
reg    ap_idle_pp0;
wire    ap_enable_pp0;

// power-on initialization
initial begin
#0 ap_CS_fsm = 12'd1;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_condition_pp0_exit_iter0_state8) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state7)) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((((1'b0 == ap_block_pp0_stage3_subdone) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end else if ((1'b1 == ap_CS_fsm_state7)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln60_reg_1768 == 1'd1))) begin
        i_0_reg_942 <= i_reg_1772;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        i_0_reg_942 <= 31'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        i_reg_1772 <= i_fu_973_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln60_reg_1768 <= icmp_ln60_fu_968_p2;
        icmp_ln60_reg_1768_pp0_iter1_reg <= icmp_ln60_reg_1768;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1) & (icmp_ln60_reg_1768 == 1'd1))) begin
        p_Result_3_0_1_reg_1787 <= {{m_axi_in_act_V_RDATA[15:8]}};
        p_Result_3_0_2_reg_1792 <= {{m_axi_in_act_V_RDATA[23:16]}};
        p_Result_3_0_3_reg_1797 <= {{m_axi_in_act_V_RDATA[31:24]}};
        p_Result_3_0_4_reg_1802 <= {{m_axi_in_act_V_RDATA[39:32]}};
        p_Result_3_0_5_reg_1807 <= {{m_axi_in_act_V_RDATA[47:40]}};
        p_Result_3_0_6_reg_1812 <= {{m_axi_in_act_V_RDATA[55:48]}};
        p_Result_3_0_7_reg_1817 <= {{m_axi_in_act_V_RDATA[63:56]}};
        p_Result_3_1_1_reg_1827 <= {{m_axi_in_act_V_RDATA[79:72]}};
        p_Result_3_1_2_reg_1832 <= {{m_axi_in_act_V_RDATA[87:80]}};
        p_Result_3_1_3_reg_1837 <= {{m_axi_in_act_V_RDATA[95:88]}};
        p_Result_3_1_4_reg_1842 <= {{m_axi_in_act_V_RDATA[103:96]}};
        p_Result_3_1_5_reg_1847 <= {{m_axi_in_act_V_RDATA[111:104]}};
        p_Result_3_1_6_reg_1852 <= {{m_axi_in_act_V_RDATA[119:112]}};
        p_Result_3_1_7_reg_1857 <= {{m_axi_in_act_V_RDATA[127:120]}};
        p_Result_3_1_reg_1822 <= {{m_axi_in_act_V_RDATA[71:64]}};
        p_Result_3_2_1_reg_1867 <= {{m_axi_in_act_V_RDATA[143:136]}};
        p_Result_3_2_2_reg_1872 <= {{m_axi_in_act_V_RDATA[151:144]}};
        p_Result_3_2_3_reg_1877 <= {{m_axi_in_act_V_RDATA[159:152]}};
        p_Result_3_2_4_reg_1882 <= {{m_axi_in_act_V_RDATA[167:160]}};
        p_Result_3_2_5_reg_1887 <= {{m_axi_in_act_V_RDATA[175:168]}};
        p_Result_3_2_6_reg_1892 <= {{m_axi_in_act_V_RDATA[183:176]}};
        p_Result_3_2_7_reg_1897 <= {{m_axi_in_act_V_RDATA[191:184]}};
        p_Result_3_2_reg_1862 <= {{m_axi_in_act_V_RDATA[135:128]}};
        p_Result_3_3_1_reg_1907 <= {{m_axi_in_act_V_RDATA[207:200]}};
        p_Result_3_3_2_reg_1912 <= {{m_axi_in_act_V_RDATA[215:208]}};
        p_Result_3_3_3_reg_1917 <= {{m_axi_in_act_V_RDATA[223:216]}};
        p_Result_3_3_4_reg_1922 <= {{m_axi_in_act_V_RDATA[231:224]}};
        p_Result_3_3_5_reg_1927 <= {{m_axi_in_act_V_RDATA[239:232]}};
        p_Result_3_3_6_reg_1932 <= {{m_axi_in_act_V_RDATA[247:240]}};
        p_Result_3_3_7_reg_1937 <= {{m_axi_in_act_V_RDATA[255:248]}};
        p_Result_3_3_reg_1902 <= {{m_axi_in_act_V_RDATA[199:192]}};
        p_Result_3_4_1_reg_1947 <= {{m_axi_in_act_V_RDATA[271:264]}};
        p_Result_3_4_2_reg_1952 <= {{m_axi_in_act_V_RDATA[279:272]}};
        p_Result_3_4_3_reg_1957 <= {{m_axi_in_act_V_RDATA[287:280]}};
        p_Result_3_4_4_reg_1962 <= {{m_axi_in_act_V_RDATA[295:288]}};
        p_Result_3_4_5_reg_1967 <= {{m_axi_in_act_V_RDATA[303:296]}};
        p_Result_3_4_6_reg_1972 <= {{m_axi_in_act_V_RDATA[311:304]}};
        p_Result_3_4_7_reg_1977 <= {{m_axi_in_act_V_RDATA[319:312]}};
        p_Result_3_4_reg_1942 <= {{m_axi_in_act_V_RDATA[263:256]}};
        p_Result_3_5_1_reg_1987 <= {{m_axi_in_act_V_RDATA[335:328]}};
        p_Result_3_5_2_reg_1992 <= {{m_axi_in_act_V_RDATA[343:336]}};
        p_Result_3_5_3_reg_1997 <= {{m_axi_in_act_V_RDATA[351:344]}};
        p_Result_3_5_4_reg_2002 <= {{m_axi_in_act_V_RDATA[359:352]}};
        p_Result_3_5_5_reg_2007 <= {{m_axi_in_act_V_RDATA[367:360]}};
        p_Result_3_5_6_reg_2012 <= {{m_axi_in_act_V_RDATA[375:368]}};
        p_Result_3_5_7_reg_2017 <= {{m_axi_in_act_V_RDATA[383:376]}};
        p_Result_3_5_reg_1982 <= {{m_axi_in_act_V_RDATA[327:320]}};
        p_Result_3_6_1_reg_2027 <= {{m_axi_in_act_V_RDATA[399:392]}};
        p_Result_3_6_2_reg_2032 <= {{m_axi_in_act_V_RDATA[407:400]}};
        p_Result_3_6_3_reg_2037 <= {{m_axi_in_act_V_RDATA[415:408]}};
        p_Result_3_6_4_reg_2042 <= {{m_axi_in_act_V_RDATA[423:416]}};
        p_Result_3_6_5_reg_2047 <= {{m_axi_in_act_V_RDATA[431:424]}};
        p_Result_3_6_6_reg_2052 <= {{m_axi_in_act_V_RDATA[439:432]}};
        p_Result_3_6_7_reg_2057 <= {{m_axi_in_act_V_RDATA[447:440]}};
        p_Result_3_6_reg_2022 <= {{m_axi_in_act_V_RDATA[391:384]}};
        p_Result_3_7_1_reg_2067 <= {{m_axi_in_act_V_RDATA[463:456]}};
        p_Result_3_7_2_reg_2072 <= {{m_axi_in_act_V_RDATA[471:464]}};
        p_Result_3_7_3_reg_2077 <= {{m_axi_in_act_V_RDATA[479:472]}};
        p_Result_3_7_4_reg_2082 <= {{m_axi_in_act_V_RDATA[487:480]}};
        p_Result_3_7_5_reg_2087 <= {{m_axi_in_act_V_RDATA[495:488]}};
        p_Result_3_7_6_reg_2092 <= {{m_axi_in_act_V_RDATA[503:496]}};
        p_Result_3_7_7_reg_2097 <= {{m_axi_in_act_V_RDATA[511:504]}};
        p_Result_3_7_reg_2062 <= {{m_axi_in_act_V_RDATA[455:448]}};
        trunc_ln647_reg_1782 <= trunc_ln647_fu_983_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2) & (icmp_ln60_reg_1768 == 1'd1))) begin
        shl_ln_reg_2102[31 : 3] <= shl_ln_fu_1617_p3[31 : 3];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln60_fu_968_p2 == 1'd1))) begin
        trunc_ln69_reg_1777 <= trunc_ln69_fu_979_p1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1))) begin
        act_buff_0_V_address0 = sext_ln69_6_fu_1727_p1;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        act_buff_0_V_address0 = sext_ln69_4_fu_1693_p1;
    end else if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        act_buff_0_V_address0 = sext_ln69_2_fu_1659_p1;
    end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        act_buff_0_V_address0 = sext_ln69_fu_1624_p1;
    end else begin
        act_buff_0_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1))) begin
        act_buff_0_V_address1 = sext_ln69_7_fu_1744_p1;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        act_buff_0_V_address1 = sext_ln69_5_fu_1710_p1;
    end else if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        act_buff_0_V_address1 = sext_ln69_3_fu_1676_p1;
    end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        act_buff_0_V_address1 = sext_ln69_1_fu_1642_p1;
    end else begin
        act_buff_0_V_address1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        act_buff_0_V_ce0 = 1'b1;
    end else begin
        act_buff_0_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        act_buff_0_V_ce1 = 1'b1;
    end else begin
        act_buff_0_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1))) begin
        act_buff_0_V_d0 = p_Result_3_6_reg_2022;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        act_buff_0_V_d0 = p_Result_3_4_reg_1942;
    end else if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        act_buff_0_V_d0 = p_Result_3_2_reg_1862;
    end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        act_buff_0_V_d0 = trunc_ln647_reg_1782;
    end else begin
        act_buff_0_V_d0 = 'bx;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1))) begin
        act_buff_0_V_d1 = p_Result_3_7_reg_2062;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        act_buff_0_V_d1 = p_Result_3_5_reg_1982;
    end else if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        act_buff_0_V_d1 = p_Result_3_3_reg_1902;
    end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        act_buff_0_V_d1 = p_Result_3_1_reg_1822;
    end else begin
        act_buff_0_V_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln60_reg_1768 == 1'd1)) | ((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln60_reg_1768 == 1'd1)) | ((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln60_reg_1768 == 1'd1)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (icmp_ln60_reg_1768_pp0_iter1_reg == 1'd1)))) begin
        act_buff_0_V_we0 = 1'b1;
    end else begin
        act_buff_0_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln60_reg_1768 == 1'd1)) | ((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln60_reg_1768 == 1'd1)) | ((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln60_reg_1768 == 1'd1)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (icmp_ln60_reg_1768_pp0_iter1_reg == 1'd1)))) begin
        act_buff_0_V_we1 = 1'b1;
    end else begin
        act_buff_0_V_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1))) begin
        act_buff_1_V_address0 = sext_ln69_6_fu_1727_p1;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        act_buff_1_V_address0 = sext_ln69_4_fu_1693_p1;
    end else if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        act_buff_1_V_address0 = sext_ln69_2_fu_1659_p1;
    end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        act_buff_1_V_address0 = sext_ln69_fu_1624_p1;
    end else begin
        act_buff_1_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1))) begin
        act_buff_1_V_address1 = sext_ln69_7_fu_1744_p1;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        act_buff_1_V_address1 = sext_ln69_5_fu_1710_p1;
    end else if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        act_buff_1_V_address1 = sext_ln69_3_fu_1676_p1;
    end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        act_buff_1_V_address1 = sext_ln69_1_fu_1642_p1;
    end else begin
        act_buff_1_V_address1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        act_buff_1_V_ce0 = 1'b1;
    end else begin
        act_buff_1_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        act_buff_1_V_ce1 = 1'b1;
    end else begin
        act_buff_1_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1))) begin
        act_buff_1_V_d0 = p_Result_3_6_1_reg_2027;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        act_buff_1_V_d0 = p_Result_3_4_1_reg_1947;
    end else if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        act_buff_1_V_d0 = p_Result_3_2_1_reg_1867;
    end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        act_buff_1_V_d0 = p_Result_3_0_1_reg_1787;
    end else begin
        act_buff_1_V_d0 = 'bx;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1))) begin
        act_buff_1_V_d1 = p_Result_3_7_1_reg_2067;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        act_buff_1_V_d1 = p_Result_3_5_1_reg_1987;
    end else if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        act_buff_1_V_d1 = p_Result_3_3_1_reg_1907;
    end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        act_buff_1_V_d1 = p_Result_3_1_1_reg_1827;
    end else begin
        act_buff_1_V_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln60_reg_1768 == 1'd1)) | ((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln60_reg_1768 == 1'd1)) | ((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln60_reg_1768 == 1'd1)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (icmp_ln60_reg_1768_pp0_iter1_reg == 1'd1)))) begin
        act_buff_1_V_we0 = 1'b1;
    end else begin
        act_buff_1_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln60_reg_1768 == 1'd1)) | ((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln60_reg_1768 == 1'd1)) | ((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln60_reg_1768 == 1'd1)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (icmp_ln60_reg_1768_pp0_iter1_reg == 1'd1)))) begin
        act_buff_1_V_we1 = 1'b1;
    end else begin
        act_buff_1_V_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1))) begin
        act_buff_2_V_address0 = sext_ln69_6_fu_1727_p1;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        act_buff_2_V_address0 = sext_ln69_4_fu_1693_p1;
    end else if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        act_buff_2_V_address0 = sext_ln69_2_fu_1659_p1;
    end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        act_buff_2_V_address0 = sext_ln69_fu_1624_p1;
    end else begin
        act_buff_2_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1))) begin
        act_buff_2_V_address1 = sext_ln69_7_fu_1744_p1;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        act_buff_2_V_address1 = sext_ln69_5_fu_1710_p1;
    end else if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        act_buff_2_V_address1 = sext_ln69_3_fu_1676_p1;
    end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        act_buff_2_V_address1 = sext_ln69_1_fu_1642_p1;
    end else begin
        act_buff_2_V_address1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        act_buff_2_V_ce0 = 1'b1;
    end else begin
        act_buff_2_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        act_buff_2_V_ce1 = 1'b1;
    end else begin
        act_buff_2_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1))) begin
        act_buff_2_V_d0 = p_Result_3_6_2_reg_2032;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        act_buff_2_V_d0 = p_Result_3_4_2_reg_1952;
    end else if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        act_buff_2_V_d0 = p_Result_3_2_2_reg_1872;
    end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        act_buff_2_V_d0 = p_Result_3_0_2_reg_1792;
    end else begin
        act_buff_2_V_d0 = 'bx;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1))) begin
        act_buff_2_V_d1 = p_Result_3_7_2_reg_2072;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        act_buff_2_V_d1 = p_Result_3_5_2_reg_1992;
    end else if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        act_buff_2_V_d1 = p_Result_3_3_2_reg_1912;
    end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        act_buff_2_V_d1 = p_Result_3_1_2_reg_1832;
    end else begin
        act_buff_2_V_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln60_reg_1768 == 1'd1)) | ((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln60_reg_1768 == 1'd1)) | ((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln60_reg_1768 == 1'd1)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (icmp_ln60_reg_1768_pp0_iter1_reg == 1'd1)))) begin
        act_buff_2_V_we0 = 1'b1;
    end else begin
        act_buff_2_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln60_reg_1768 == 1'd1)) | ((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln60_reg_1768 == 1'd1)) | ((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln60_reg_1768 == 1'd1)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (icmp_ln60_reg_1768_pp0_iter1_reg == 1'd1)))) begin
        act_buff_2_V_we1 = 1'b1;
    end else begin
        act_buff_2_V_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1))) begin
        act_buff_3_V_address0 = sext_ln69_6_fu_1727_p1;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        act_buff_3_V_address0 = sext_ln69_4_fu_1693_p1;
    end else if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        act_buff_3_V_address0 = sext_ln69_2_fu_1659_p1;
    end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        act_buff_3_V_address0 = sext_ln69_fu_1624_p1;
    end else begin
        act_buff_3_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1))) begin
        act_buff_3_V_address1 = sext_ln69_7_fu_1744_p1;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        act_buff_3_V_address1 = sext_ln69_5_fu_1710_p1;
    end else if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        act_buff_3_V_address1 = sext_ln69_3_fu_1676_p1;
    end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        act_buff_3_V_address1 = sext_ln69_1_fu_1642_p1;
    end else begin
        act_buff_3_V_address1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        act_buff_3_V_ce0 = 1'b1;
    end else begin
        act_buff_3_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        act_buff_3_V_ce1 = 1'b1;
    end else begin
        act_buff_3_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1))) begin
        act_buff_3_V_d0 = p_Result_3_6_3_reg_2037;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        act_buff_3_V_d0 = p_Result_3_4_3_reg_1957;
    end else if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        act_buff_3_V_d0 = p_Result_3_2_3_reg_1877;
    end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        act_buff_3_V_d0 = p_Result_3_0_3_reg_1797;
    end else begin
        act_buff_3_V_d0 = 'bx;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1))) begin
        act_buff_3_V_d1 = p_Result_3_7_3_reg_2077;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        act_buff_3_V_d1 = p_Result_3_5_3_reg_1997;
    end else if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        act_buff_3_V_d1 = p_Result_3_3_3_reg_1917;
    end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        act_buff_3_V_d1 = p_Result_3_1_3_reg_1837;
    end else begin
        act_buff_3_V_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln60_reg_1768 == 1'd1)) | ((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln60_reg_1768 == 1'd1)) | ((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln60_reg_1768 == 1'd1)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (icmp_ln60_reg_1768_pp0_iter1_reg == 1'd1)))) begin
        act_buff_3_V_we0 = 1'b1;
    end else begin
        act_buff_3_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln60_reg_1768 == 1'd1)) | ((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln60_reg_1768 == 1'd1)) | ((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln60_reg_1768 == 1'd1)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (icmp_ln60_reg_1768_pp0_iter1_reg == 1'd1)))) begin
        act_buff_3_V_we1 = 1'b1;
    end else begin
        act_buff_3_V_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1))) begin
        act_buff_4_V_address0 = sext_ln69_6_fu_1727_p1;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        act_buff_4_V_address0 = sext_ln69_4_fu_1693_p1;
    end else if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        act_buff_4_V_address0 = sext_ln69_2_fu_1659_p1;
    end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        act_buff_4_V_address0 = sext_ln69_fu_1624_p1;
    end else begin
        act_buff_4_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1))) begin
        act_buff_4_V_address1 = sext_ln69_7_fu_1744_p1;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        act_buff_4_V_address1 = sext_ln69_5_fu_1710_p1;
    end else if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        act_buff_4_V_address1 = sext_ln69_3_fu_1676_p1;
    end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        act_buff_4_V_address1 = sext_ln69_1_fu_1642_p1;
    end else begin
        act_buff_4_V_address1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        act_buff_4_V_ce0 = 1'b1;
    end else begin
        act_buff_4_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        act_buff_4_V_ce1 = 1'b1;
    end else begin
        act_buff_4_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1))) begin
        act_buff_4_V_d0 = p_Result_3_6_4_reg_2042;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        act_buff_4_V_d0 = p_Result_3_4_4_reg_1962;
    end else if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        act_buff_4_V_d0 = p_Result_3_2_4_reg_1882;
    end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        act_buff_4_V_d0 = p_Result_3_0_4_reg_1802;
    end else begin
        act_buff_4_V_d0 = 'bx;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1))) begin
        act_buff_4_V_d1 = p_Result_3_7_4_reg_2082;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        act_buff_4_V_d1 = p_Result_3_5_4_reg_2002;
    end else if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        act_buff_4_V_d1 = p_Result_3_3_4_reg_1922;
    end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        act_buff_4_V_d1 = p_Result_3_1_4_reg_1842;
    end else begin
        act_buff_4_V_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln60_reg_1768 == 1'd1)) | ((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln60_reg_1768 == 1'd1)) | ((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln60_reg_1768 == 1'd1)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (icmp_ln60_reg_1768_pp0_iter1_reg == 1'd1)))) begin
        act_buff_4_V_we0 = 1'b1;
    end else begin
        act_buff_4_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln60_reg_1768 == 1'd1)) | ((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln60_reg_1768 == 1'd1)) | ((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln60_reg_1768 == 1'd1)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (icmp_ln60_reg_1768_pp0_iter1_reg == 1'd1)))) begin
        act_buff_4_V_we1 = 1'b1;
    end else begin
        act_buff_4_V_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1))) begin
        act_buff_5_V_address0 = sext_ln69_6_fu_1727_p1;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        act_buff_5_V_address0 = sext_ln69_4_fu_1693_p1;
    end else if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        act_buff_5_V_address0 = sext_ln69_2_fu_1659_p1;
    end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        act_buff_5_V_address0 = sext_ln69_fu_1624_p1;
    end else begin
        act_buff_5_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1))) begin
        act_buff_5_V_address1 = sext_ln69_7_fu_1744_p1;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        act_buff_5_V_address1 = sext_ln69_5_fu_1710_p1;
    end else if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        act_buff_5_V_address1 = sext_ln69_3_fu_1676_p1;
    end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        act_buff_5_V_address1 = sext_ln69_1_fu_1642_p1;
    end else begin
        act_buff_5_V_address1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        act_buff_5_V_ce0 = 1'b1;
    end else begin
        act_buff_5_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        act_buff_5_V_ce1 = 1'b1;
    end else begin
        act_buff_5_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1))) begin
        act_buff_5_V_d0 = p_Result_3_6_5_reg_2047;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        act_buff_5_V_d0 = p_Result_3_4_5_reg_1967;
    end else if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        act_buff_5_V_d0 = p_Result_3_2_5_reg_1887;
    end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        act_buff_5_V_d0 = p_Result_3_0_5_reg_1807;
    end else begin
        act_buff_5_V_d0 = 'bx;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1))) begin
        act_buff_5_V_d1 = p_Result_3_7_5_reg_2087;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        act_buff_5_V_d1 = p_Result_3_5_5_reg_2007;
    end else if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        act_buff_5_V_d1 = p_Result_3_3_5_reg_1927;
    end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        act_buff_5_V_d1 = p_Result_3_1_5_reg_1847;
    end else begin
        act_buff_5_V_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln60_reg_1768 == 1'd1)) | ((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln60_reg_1768 == 1'd1)) | ((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln60_reg_1768 == 1'd1)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (icmp_ln60_reg_1768_pp0_iter1_reg == 1'd1)))) begin
        act_buff_5_V_we0 = 1'b1;
    end else begin
        act_buff_5_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln60_reg_1768 == 1'd1)) | ((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln60_reg_1768 == 1'd1)) | ((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln60_reg_1768 == 1'd1)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (icmp_ln60_reg_1768_pp0_iter1_reg == 1'd1)))) begin
        act_buff_5_V_we1 = 1'b1;
    end else begin
        act_buff_5_V_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1))) begin
        act_buff_6_V_address0 = sext_ln69_6_fu_1727_p1;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        act_buff_6_V_address0 = sext_ln69_4_fu_1693_p1;
    end else if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        act_buff_6_V_address0 = sext_ln69_2_fu_1659_p1;
    end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        act_buff_6_V_address0 = sext_ln69_fu_1624_p1;
    end else begin
        act_buff_6_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1))) begin
        act_buff_6_V_address1 = sext_ln69_7_fu_1744_p1;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        act_buff_6_V_address1 = sext_ln69_5_fu_1710_p1;
    end else if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        act_buff_6_V_address1 = sext_ln69_3_fu_1676_p1;
    end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        act_buff_6_V_address1 = sext_ln69_1_fu_1642_p1;
    end else begin
        act_buff_6_V_address1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        act_buff_6_V_ce0 = 1'b1;
    end else begin
        act_buff_6_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        act_buff_6_V_ce1 = 1'b1;
    end else begin
        act_buff_6_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1))) begin
        act_buff_6_V_d0 = p_Result_3_6_6_reg_2052;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        act_buff_6_V_d0 = p_Result_3_4_6_reg_1972;
    end else if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        act_buff_6_V_d0 = p_Result_3_2_6_reg_1892;
    end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        act_buff_6_V_d0 = p_Result_3_0_6_reg_1812;
    end else begin
        act_buff_6_V_d0 = 'bx;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1))) begin
        act_buff_6_V_d1 = p_Result_3_7_6_reg_2092;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        act_buff_6_V_d1 = p_Result_3_5_6_reg_2012;
    end else if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        act_buff_6_V_d1 = p_Result_3_3_6_reg_1932;
    end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        act_buff_6_V_d1 = p_Result_3_1_6_reg_1852;
    end else begin
        act_buff_6_V_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln60_reg_1768 == 1'd1)) | ((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln60_reg_1768 == 1'd1)) | ((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln60_reg_1768 == 1'd1)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (icmp_ln60_reg_1768_pp0_iter1_reg == 1'd1)))) begin
        act_buff_6_V_we0 = 1'b1;
    end else begin
        act_buff_6_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln60_reg_1768 == 1'd1)) | ((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln60_reg_1768 == 1'd1)) | ((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln60_reg_1768 == 1'd1)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (icmp_ln60_reg_1768_pp0_iter1_reg == 1'd1)))) begin
        act_buff_6_V_we1 = 1'b1;
    end else begin
        act_buff_6_V_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1))) begin
        act_buff_7_V_address0 = sext_ln69_6_fu_1727_p1;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        act_buff_7_V_address0 = sext_ln69_4_fu_1693_p1;
    end else if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        act_buff_7_V_address0 = sext_ln69_2_fu_1659_p1;
    end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        act_buff_7_V_address0 = sext_ln69_fu_1624_p1;
    end else begin
        act_buff_7_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1))) begin
        act_buff_7_V_address1 = sext_ln69_7_fu_1744_p1;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        act_buff_7_V_address1 = sext_ln69_5_fu_1710_p1;
    end else if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        act_buff_7_V_address1 = sext_ln69_3_fu_1676_p1;
    end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        act_buff_7_V_address1 = sext_ln69_1_fu_1642_p1;
    end else begin
        act_buff_7_V_address1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        act_buff_7_V_ce0 = 1'b1;
    end else begin
        act_buff_7_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        act_buff_7_V_ce1 = 1'b1;
    end else begin
        act_buff_7_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1))) begin
        act_buff_7_V_d0 = p_Result_3_6_7_reg_2057;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        act_buff_7_V_d0 = p_Result_3_4_7_reg_1977;
    end else if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        act_buff_7_V_d0 = p_Result_3_2_7_reg_1897;
    end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        act_buff_7_V_d0 = p_Result_3_0_7_reg_1817;
    end else begin
        act_buff_7_V_d0 = 'bx;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1))) begin
        act_buff_7_V_d1 = p_Result_3_7_7_reg_2097;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        act_buff_7_V_d1 = p_Result_3_5_7_reg_2017;
    end else if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        act_buff_7_V_d1 = p_Result_3_3_7_reg_1937;
    end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        act_buff_7_V_d1 = p_Result_3_1_7_reg_1857;
    end else begin
        act_buff_7_V_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln60_reg_1768 == 1'd1)) | ((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln60_reg_1768 == 1'd1)) | ((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln60_reg_1768 == 1'd1)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (icmp_ln60_reg_1768_pp0_iter1_reg == 1'd1)))) begin
        act_buff_7_V_we0 = 1'b1;
    end else begin
        act_buff_7_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln60_reg_1768 == 1'd1)) | ((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln60_reg_1768 == 1'd1)) | ((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln60_reg_1768 == 1'd1)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (icmp_ln60_reg_1768_pp0_iter1_reg == 1'd1)))) begin
        act_buff_7_V_we1 = 1'b1;
    end else begin
        act_buff_7_V_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((icmp_ln60_fu_968_p2 == 1'd0)) begin
        ap_condition_pp0_exit_iter0_state8 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state8 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state14) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln60_reg_1768 == 1'd1))) begin
        ap_phi_mux_i_0_phi_fu_946_p4 = i_reg_1772;
    end else begin
        ap_phi_mux_i_0_phi_fu_946_p4 = i_0_reg_942;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        in_act_V_blk_n_AR = m_axi_in_act_V_ARREADY;
    end else begin
        in_act_V_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (icmp_ln60_reg_1768 == 1'd1) & (1'b0 == ap_block_pp0_stage1))) begin
        in_act_V_blk_n_R = m_axi_in_act_V_RVALID;
    end else begin
        in_act_V_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if ((~((m_axi_in_act_V_ARREADY == 1'b0) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        m_axi_in_act_V_ARVALID = 1'b1;
    end else begin
        m_axi_in_act_V_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (icmp_ln60_reg_1768 == 1'd1))) begin
        m_axi_in_act_V_RREADY = 1'b1;
    end else begin
        m_axi_in_act_V_RREADY = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((m_axi_in_act_V_ARREADY == 1'b0) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((icmp_ln60_fu_968_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else if (((icmp_ln60_fu_968_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((~((1'b0 == ap_block_pp0_stage1_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b0)) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else if (((1'b0 == ap_block_pp0_stage1_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        ap_ST_fsm_pp0_stage3 : begin
            if ((1'b0 == ap_block_pp0_stage3_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd8];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_pp0_stage3 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_11001 = ((m_axi_in_act_V_RVALID == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln60_reg_1768 == 1'd1));
end

always @ (*) begin
    ap_block_pp0_stage1_subdone = ((m_axi_in_act_V_RVALID == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln60_reg_1768 == 1'd1));
end

assign ap_block_pp0_stage2 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_subdone = ~(1'b1 == 1'b1);

assign ap_block_state10_pp0_stage2_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage3_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp0_stage1_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state9_pp0_stage1_iter0 = ((m_axi_in_act_V_RVALID == 1'b0) & (icmp_ln60_reg_1768 == 1'd1));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign i_fu_973_p2 = (ap_phi_mux_i_0_phi_fu_946_p4 + 31'd1);

assign icmp_ln60_fu_968_p2 = (($signed(zext_ln60_fu_964_p1) < $signed(act_load_length)) ? 1'b1 : 1'b0);

assign m_axi_in_act_V_ARADDR = zext_ln57_fu_953_p1;

assign m_axi_in_act_V_ARBURST = 2'd0;

assign m_axi_in_act_V_ARCACHE = 4'd0;

assign m_axi_in_act_V_ARID = 1'd0;

assign m_axi_in_act_V_ARLEN = act_load_length;

assign m_axi_in_act_V_ARLOCK = 2'd0;

assign m_axi_in_act_V_ARPROT = 3'd0;

assign m_axi_in_act_V_ARQOS = 4'd0;

assign m_axi_in_act_V_ARREGION = 4'd0;

assign m_axi_in_act_V_ARSIZE = 3'd0;

assign m_axi_in_act_V_ARUSER = 1'd0;

assign m_axi_in_act_V_AWADDR = 32'd0;

assign m_axi_in_act_V_AWBURST = 2'd0;

assign m_axi_in_act_V_AWCACHE = 4'd0;

assign m_axi_in_act_V_AWID = 1'd0;

assign m_axi_in_act_V_AWLEN = 32'd0;

assign m_axi_in_act_V_AWLOCK = 2'd0;

assign m_axi_in_act_V_AWPROT = 3'd0;

assign m_axi_in_act_V_AWQOS = 4'd0;

assign m_axi_in_act_V_AWREGION = 4'd0;

assign m_axi_in_act_V_AWSIZE = 3'd0;

assign m_axi_in_act_V_AWUSER = 1'd0;

assign m_axi_in_act_V_AWVALID = 1'b0;

assign m_axi_in_act_V_BREADY = 1'b0;

assign m_axi_in_act_V_WDATA = 512'd0;

assign m_axi_in_act_V_WID = 1'd0;

assign m_axi_in_act_V_WLAST = 1'b0;

assign m_axi_in_act_V_WSTRB = 64'd0;

assign m_axi_in_act_V_WUSER = 1'd0;

assign m_axi_in_act_V_WVALID = 1'b0;

assign or_ln69_1_fu_1654_p2 = (shl_ln_reg_2102 | 32'd2);

assign or_ln69_2_fu_1671_p2 = (shl_ln_reg_2102 | 32'd3);

assign or_ln69_3_fu_1688_p2 = (shl_ln_reg_2102 | 32'd4);

assign or_ln69_4_fu_1705_p2 = (shl_ln_reg_2102 | 32'd5);

assign or_ln69_5_fu_1722_p2 = (shl_ln_reg_2102 | 32'd6);

assign or_ln69_6_fu_1739_p2 = (shl_ln_reg_2102 | 32'd7);

assign or_ln69_fu_1636_p2 = (shl_ln_fu_1617_p3 | 32'd1);

assign sext_ln69_1_fu_1642_p1 = $signed(or_ln69_fu_1636_p2);

assign sext_ln69_2_fu_1659_p1 = $signed(or_ln69_1_fu_1654_p2);

assign sext_ln69_3_fu_1676_p1 = $signed(or_ln69_2_fu_1671_p2);

assign sext_ln69_4_fu_1693_p1 = $signed(or_ln69_3_fu_1688_p2);

assign sext_ln69_5_fu_1710_p1 = $signed(or_ln69_4_fu_1705_p2);

assign sext_ln69_6_fu_1727_p1 = $signed(or_ln69_5_fu_1722_p2);

assign sext_ln69_7_fu_1744_p1 = $signed(or_ln69_6_fu_1739_p2);

assign sext_ln69_fu_1624_p1 = shl_ln_fu_1617_p3;

assign shl_ln_fu_1617_p3 = {{trunc_ln69_reg_1777}, {3'd0}};

assign trunc_ln647_fu_983_p1 = m_axi_in_act_V_RDATA[7:0];

assign trunc_ln69_fu_979_p1 = ap_phi_mux_i_0_phi_fu_946_p4[28:0];

assign zext_ln57_fu_953_p1 = in_act_V_offset;

assign zext_ln60_fu_964_p1 = ap_phi_mux_i_0_phi_fu_946_p4;

always @ (posedge ap_clk) begin
    shl_ln_reg_2102[2:0] <= 3'b000;
end

endmodule //LoadAct
